openapi: 3.0.0
info:
  title: Atendimento Médico API
  version: 1.0.0

paths:
  /usuarios:
    get:
      summary: Listar todos os usuários
      responses:
        '200':
          description: Lista de usuários cadastrados
          content:
            application/json:
              example:
                - cpf: 000.000.000-01
                  nome: Carlos Sérgio Batalha Filho
                  data_nasc: 01/01/1990
                  id: admin
                - cpf: 000.000.000-02
                  nome: Gabriel Victor de Souza Fernandes
                  data_nasc: 02/02/1995
                  id: comum

    post:
      summary: Cadastrar usuário
      requestBody:
        content:
          application/json:
            example:
              cpf: 000.000.000-03
              nome: Novo Usuário
              data_nasc: 03/03/2000
              id: comum
      responses:
        '201':
          description: Usuário criado com sucesso
        '400':
          description: Parâmetros faltando ou inválidos

  /usuarios/{cpf}:
    get:
      summary: Obter dados de um usuário pelo CPF
      security:
        - bearer: []
      parameters:
        - in: path
          name: cpf
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Dados do usuário encontrados
          content:
            application/json:
              example:
                cpf: 000.000.000-01
                nome: Carlos Sérgio Batalha Filho
                data_nasc: 01/01/1990
                id: admin
        '404':
          description: Usuário não encontrado

    put:
      summary: Alterar dados de um usuário pelo CPF
      security:
        - bearer: []
      
      parameters:
        - in: path
          name: cpf
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            example:
              cpf: 000.000.000-01
              nome: Novo Nome
              data_nasc: 01/01/1990
              id: admin
      responses:
        '200':
          description: Dados do usuário alterados com sucesso
        '403':
          description: Usuário não tem permissão para fazer a alteração
        '404':
          description: Usuário não encontrado

    delete:
      summary: Apagar um usuário pelo CPF
      security:
        - bearer: []
      
      parameters:
        - in: path
          name: cpf
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Usuário apagado com sucesso
        '403':
          description: Usuário não tem permissão para apagar
        '404':
          description: Usuário não encontrado

components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT 
